version: "2"
run:
  tests: true
  build-tags:
    - fts5
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - modernize
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - modernize
        text: "omitzero:"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
